name: ghost_bank
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  barcode_widget: ^2.0.4
  dotted_border: ^2.0.0+3
  dotted_line: ^3.2.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_credit_card_ui: ^0.0.4
  flutter_local_notifications: ^15.1.1
  flutter_native_splash: ^2.3.2
  flutter_riverpod: ^2.4.0
  intl: ^0.18.1
  share_plus: ^7.2.1


flutter_native_splash:
  color: '#ffffff'
  image: lib/assets/images/ghost.png
  android: true
  web: true
  ios: true
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - 'lib/assets/images/'
